name: videoandconfigsharing
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Corrected Dependencies
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.2
  archive: ^4.0.4
  image: ^4.5.3
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  uuid: ^4.1.0
  livekit_client: ^2.3.6  # ✅ Removed duplicate & kept latest
  process_run: ^0.14.2  # ✅ Updated to latest stable
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1  # ✅ Updated to latest stable

flutter:
  uses-material-design: true
  assets:
    - .env
